language: node_js

node_js:
  - 'stable'
  - '4'
  - '0.10'

sudo: false

env:
  - workerCount=4

matrix:
  fast_finish: true
  include:
  - os: osx
    node_js: stable
    osx_image: xcode7.3
    env: workerCount=2

branches:
  only:
  - master
  - transforms

install:
  - npm uninstall typescript
  - npm uninstall tslint
  - npm install
  - npm update

cache:
  directories:
    - node_modules
